// Code generated by "stringer -type=CardRank,CardSuit"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ace-1]
	_ = x[Two-2]
	_ = x[Three-3]
	_ = x[Four-4]
	_ = x[Five-5]
	_ = x[Six-6]
	_ = x[Seven-7]
	_ = x[Eight-8]
	_ = x[Nine-9]
	_ = x[Ten-10]
	_ = x[Jack-11]
	_ = x[Queen-12]
	_ = x[King-13]
}

const _CardRank_name = "AceTwoThreeFourFiveSixSevenEightNineTenJackQueenKing"

var _CardRank_index = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 32, 36, 39, 43, 48, 52}

func (i CardRank) String() string {
	i -= 1
	if i >= CardRank(len(_CardRank_index)-1) {
		return "CardRank(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CardRank_name[_CardRank_index[i]:_CardRank_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Diamond-0]
	_ = x[Club-1]
	_ = x[Heart-2]
	_ = x[Spade-3]
	_ = x[Joker-4]
}

const _CardSuit_name = "DiamondClubHeartSpadeJoker"

var _CardSuit_index = [...]uint8{0, 7, 11, 16, 21, 26}

func (i CardSuit) String() string {
	if i >= CardSuit(len(_CardSuit_index)-1) {
		return "CardSuit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardSuit_name[_CardSuit_index[i]:_CardSuit_index[i+1]]
}
